#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ActorNet/Js.cshtml")]
    public partial class _Views_ActorNet_Js_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_ActorNet_Js_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"var ActorsNet = {};
var __guid = function() {
function s4() {
return Math.floor((1 + Math.random()) * 0x10000)
.toString(16)
.substring(1);
}

return s4() + s4() + ""-"" + s4() + ""-"" + s4() + ""-"" +
s4() + ""-"" + s4() + s4() + s4();
};
var __createMessage = function(messageType)
{
return {
MessageTypeName: messageType,
MessageData: {},
Guid: __guid(),
setMessageData: function(data) {
this.MessageData = data;
}
};
};
");

            
            #line 23 "..\..\Views\ActorNet\Js.cshtml"
 foreach (var actorSystem in ViewBag.MessagesBySystem)
{

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("\r\n        ActorsNet.");

            
            #line 26 "..\..\Views\ActorNet\Js.cshtml"
              Write(actorSystem.Key);

            
            #line default
            #line hidden
WriteLiteral(" = {\r\n        create : function(){\r\n        return new ActorsNetSystem(\"");

            
            #line 28 "..\..\Views\ActorNet\Js.cshtml"
                                Write(actorSystem.Key);

            
            #line default
            #line hidden
WriteLiteral("\")\r\n        }\r\n        };\r\n");

            
            #line 31 "..\..\Views\ActorNet\Js.cshtml"
        
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\ActorNet\Js.cshtml"
         foreach (var messageTypeName in actorSystem.Value)
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n\r\n                ActorsNet.");

            
            #line 35 "..\..\Views\ActorNet\Js.cshtml"
                      Write(actorSystem.Key.Replace(".", "_"));

            
            #line default
            #line hidden
WriteLiteral(".");

            
            #line 35 "..\..\Views\ActorNet\Js.cshtml"
                                                           Write(messageTypeName.Replace(".", "_"));

            
            #line default
            #line hidden
WriteLiteral(" = {\r\n                create : function(){\r\n                var msg =__createMess" +
"age(\"");

            
            #line 37 "..\..\Views\ActorNet\Js.cshtml"
                                      Write(messageTypeName);

            
            #line default
            #line hidden
WriteLiteral("\");\r\n                msg.setMessageData(\r\n");

WriteLiteral("                ");

            
            #line 39 "..\..\Views\ActorNet\Js.cshtml"
           Write(Html.Raw(ViewBag.JsonStringFromMessageType[messageTypeName]));

            
            #line default
            #line hidden
WriteLiteral("\r\n                );\r\n                return msg;\r\n                }\r\n           " +
"     };\r\n            ");

WriteLiteral("\r\n");

            
            #line 45 "..\..\Views\ActorNet\Js.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("\r\n");

            
            #line 47 "..\..\Views\ActorNet\Js.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
