#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ActorNet/Js.cshtml")]
    public partial class _Views_ActorNet_Js_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_ActorNet_Js_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"var ActorsNet = function(){
    var ActorsNet = {};

    var __guid = function() {
        function s4() {
            return Math.floor((1 + Math.random()) * 0x10000)
                    .toString(16)
                    .substring(1);
        }
        return s4() + s4() + ""-"" + s4() + ""-"" + s4() + ""-"" + s4() + ""-"" + s4() + s4() + s4();
    };

    var __createMessage = function(messageType)
{
        var Message = function(msgType) {
            this.payload = { '$type': msgType };
            this.guid = __guid();
        };
        Message.prototype.setMessageData = function(data) {
            Object.assign(this.payload, data);
        };
        return new Message(messageType);
    };
");

            
            #line 24 "..\..\Views\ActorNet\Js.cshtml"
    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\ActorNet\Js.cshtml"
     foreach (var actorSystem in ViewBag.MessagesBySystem)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n            ActorsNet.");

            
            #line 27 "..\..\Views\ActorNet\Js.cshtml"
                  Write(actorSystem.Key);

            
            #line default
            #line hidden
WriteLiteral(" = {\r\n                create : function(){\r\n                    return new Actors" +
"NetSystem(\"");

            
            #line 29 "..\..\Views\ActorNet\Js.cshtml"
                                            Write(actorSystem.Key);

            
            #line default
            #line hidden
WriteLiteral("\")\r\n                }\r\n            };\r\n");

            
            #line 32 "..\..\Views\ActorNet\Js.cshtml"
            
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\ActorNet\Js.cshtml"
             foreach (var messageTypeName in actorSystem.Value)
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("\r\n\r\n                    ActorsNet.");

            
            #line 36 "..\..\Views\ActorNet\Js.cshtml"
                          Write(actorSystem.Key.Replace(".", "_"));

            
            #line default
            #line hidden
WriteLiteral(".");

            
            #line 36 "..\..\Views\ActorNet\Js.cshtml"
                                                               Write(messageTypeName.Replace(".", "_"));

            
            #line default
            #line hidden
WriteLiteral(" = {\r\n                        create : function(){\r\n                            v" +
"ar msg =__createMessage(\"");

            
            #line 38 "..\..\Views\ActorNet\Js.cshtml"
                                                  Write(messageTypeName);

            
            #line default
            #line hidden
WriteLiteral("\");\r\n                            msg.setMessageData(\r\n");

WriteLiteral("                                ");

            
            #line 40 "..\..\Views\ActorNet\Js.cshtml"
                           Write(Html.Raw(ViewBag.JsonStringFromMessageType[messageTypeName]));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            );\r\n                            return msg;\r\n      " +
"                  }\r\n                    };\r\n                ");

WriteLiteral("\r\n");

            
            #line 46 "..\..\Views\ActorNet\Js.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n");

            
            #line 48 "..\..\Views\ActorNet\Js.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    return ActorsNet;\r\n}();");

        }
    }
}
#pragma warning restore 1591
